application: imazon-prototype
version: 3
runtime: python
api_version: 1

default_expiration: "5d"

builtins:
- datastore_admin: on
- remote_api: on
- deferred: on

inbound_services:
- warmup

skip_files:
    config.rb
    Gemfile

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: main.py

